version: '3.9'

services:
  nginx:
    image: nginx:1.27.3@sha256:0e65e7b19ac0abab5c911b175ca20040c98200337337cbb366af24ab597927ea
    hostname: nginx
    container_name: gs724tproxy__nginx

    restart: unless-stopped

    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

      - type: volume
        source: cache_data
        target: /var/cache/nginx

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

  cloudflared:
    image: cloudflare/cloudflared:2025.1.1@sha256:bc2b3edd9eb0257a1a1fc58113e97426afe524e04b898173cd7df01442bcb4b3
    hostname: cloudflared
    container_name: gs724tproxy__cloudflared

    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      default:
      prometheus__cloudflared:
        aliases:
          - gs724tproxy__cloudflared

volumes:
  cache_data:
    name: gs724tproxy__cache_data


networks:
  default:
    name: gs724tproxy__default

  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true
